name: Mike & Kristen
favicon: null
layout_spectrum: 0.35122153465636075
typography_spectrum: 0.35812528850510716
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.06837279489263892
  lightness: 0.6180691043846309
  saturation: 0.5910482441540807
  rhythmicContrast: 0.5118917424697429
purpose: []
